### ISSUE TITLE
CT value property should not be set to anything except invalid value if the point controller is not on the number line

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-distance#2]
```
number-line-distance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/number-line-distance/number-line-distance_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1592539701703%22%2C%22timestamp%22%3A1592542747233%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value property should not be set to anything except invalid value if the point controller is not on the number line
Error: Assertion failed: value property should not be set to anything except invalid value if the point controller is not on the number line
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/number-line-distance/js/generic/view/ControllingDistanceStatement.js:61:19
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/axon/js/TinyEmitter.js:69:53)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/axon/js/Property.js:273:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/axon/js/Property.js:171:14)
at Array.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/scenery-phet/js/NumberPicker.js:333:21)
at CallbackTimer.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/axon/js/CallbackTimer.js:115:25)
at CallbackTimer.stop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/axon/js/CallbackTimer.js:87:14)
at Object.upInside (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/scenery-phet/js/buttons/FireOnHoldInputListener.js:60:18)
at FireOnHoldInputListener.buttonUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592539701703/scenery/js/input/DownUpListener.js:140:22)
id: Bayes Chrome
Snapshot from 6/18/2020, 10:08:21 PM
```

**Comment by jbphet** [comment]
@SaurabhTotey is doing most of the work on this, assigning to him.

**Comment by SaurabhTotey** [comment]
I realized the assertion I put in previously was incorrect and have now removed it. I'll wait for a few more columns of CT to show up green before I close this.
